image: openjdk:17-bullseye

pipelines:
  custom:
    develop:
      - step:
          name: Build and Deploy
          deployment: develop
          services:
            - docker
          script:
            - apt-get update && apt-get install -y zip python3-pip
            - pip3 install --upgrade awscli

            - echo "Building Docker image..."
            - docker build -t murrindindi_intgration .
            - echo "Logging in to AWS ECR..."
            - export ECR_PASSWORD=$(aws ecr get-login-password --region ap-southeast-2)
            - echo $ECR_PASSWORD | docker login --username AWS --password-stdin 120121536163.dkr.ecr.ap-southeast-2.amazonaws.com
            - VERSION=$(date +%Y%m%d%H%M%S)
            - docker tag murrindindi_intgration:latest $IMAGE_URI:$VERSION
            - docker push $IMAGE_URI:$VERSION
            - echo "Deploying Lambda function..."
            - |
              aws cloudformation deploy --template-file ./cloudformations/cloudformation.yml \
              --stack-name MurrindindiAuthorityToAsseticDev \
              --parameter-overrides \
              PrivateSubnet=$SMARTGLUE_SUBNET_ID \
              VPCId=$SMARTGLUE_VPC_ID \
              AsseticAPIBasic=$ASSETIC_API_BASIC \
              AsseticHost=$ASSETIC_HOST \
              AuthorityConfigFileName=$AUTHORITY_CONFIG_CONFIGFILE_NAME \
              CompletedEventApiKey=$COMPLETED_EVENT_API_KEY_VALUE \
              CompletedEventUrl=$COMPLETED_EVENT_URL \
              SGS3BucketName=$AWS_SG_BUCKET_NAME \
              AwsRegion=$AWS_REGION \
              AwsSecretKey=$AWS_SECRET_KEY_INTEGRATION \
              AwsAccessKey=$AWS_ACCESS_KEY_INTEGRATION \
              AuthorityClientSecret=$AUTHORITY_CLIENT_SECRET \
              AuthorityClientId=$AUTHORITY_CLIENT_ID \
              AuthorityPassword=$AUTHORITY_PASSWORD \
              AuthorityUser=$AUTHORITY_USER \
              AuthorityHost=$AUTHORITY_HOST \
              TenantIntegrationIdAsseticToCivica=$TENANT_INTEGRATION_ID_ASSETIC_TO_CIVICA_MURRINDINDI \
              TenantIntegrationIdCivicaToAssetic=$TENANT_INTEGRATION_ID_MURRINDINDI \
              TenantIdMurrindindi=$TENANT_ID_MURRINDINDI \
              ImageUri=$IMAGE_URI:$VERSION \
              --capabilities CAPABILITY_NAMED_IAM

    production:
      - step:
          name: Build and Deploy
          deployment: production
          services:
            - docker
          script:
            - apt-get update && apt-get install -y zip python3-pip
            - pip3 install --upgrade awscli

            - echo "Building Docker image..."
            - docker build -t murrindindi_intgration .
            - echo "Logging in to AWS ECR..."
            - export ECR_PASSWORD=$(aws ecr get-login-password --region ap-southeast-2)
            - echo $ECR_PASSWORD | docker login --username AWS --password-stdin 023225200251.dkr.ecr.ap-southeast-2.amazonaws.com
            - VERSION=$(date +%Y%m%d%H%M%S)
            - docker tag murrindindi_intgration:latest $IMAGE_URI:$VERSION
            - docker push $IMAGE_URI:$VERSION
            - echo "Deploying Lambda function..."
            - |
              aws cloudformation deploy --template-file ./cloudformations/cloudformation.yml \
              --stack-name MurrindindiAuthorityToAsseticDev \
              --parameter-overrides \
              PrivateSubnet=$SMARTGLUE_SUBNET_ID \
              VPCId=$SMARTGLUE_VPC_ID \
              AsseticAPIBasic=$ASSETIC_API_BASIC \
              AsseticHost=$ASSETIC_HOST \
              AuthorityConfigFileName=$AUTHORITY_CONFIG_CONFIGFILE_NAME \
              CompletedEventApiKey=$COMPLETED_EVENT_API_KEY_VALUE \
              CompletedEventUrl=$COMPLETED_EVENT_URL \
              SGS3BucketName=$AWS_SG_BUCKET_NAME \
              AwsRegion=$AWS_REGION \
              AwsSecretKey=$AWS_SECRET_KEY_INTEGRATION \
              AwsAccessKey=$AWS_ACCESS_KEY_INTEGRATION \
              AuthorityClientSecret=$AUTHORITY_CLIENT_SECRET \
              AuthorityClientId=$AUTHORITY_CLIENT_ID \
              AuthorityPassword=$AUTHORITY_PASSWORD \
              AuthorityUser=$AUTHORITY_USER \
              AuthorityHost=$AUTHORITY_HOST \
              TenantIntegrationIdAsseticToCivica=$TENANT_INTEGRATION_ID_ASSETIC_TO_CIVICA_MURRINDINDI \
              TenantIntegrationIdCivicaToAssetic=$TENANT_INTEGRATION_ID_MURRINDINDI \
              TenantIdMurrindindi=$TENANT_ID_MURRINDINDI \
              ImageUri=$IMAGE_URI:$VERSION \
              --capabilities CAPABILITY_NAMED_IAM

    run-sonar-scan-quality-gw:
      - step:
          name: Build, Test & SonarCloud Analysis
          image: maven:3.8.5-openjdk-17
          caches:
            - maven
          script:
            - git fetch origin main
            - mvn clean verify
            - mvn sonar:sonar -Dsonar.branch.name=${BITBUCKET_BRANCH} -Dsonar.organization=symphony3 -Dsonar.projectKey=murrindindi_authority_assetic_integration -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
