AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaFunctionTenant:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.example.integration.tenant.handlers.AuthorityToAsseticHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 600
      Environment:
        Variables:
          TENANT_ID: "11"
          TENANT_INTEGRATION_ID_CIVICA_TO_ASSETIC: "31"
          TENANT_INTEGRATION_ID_ASSETIC_TO_CIVICA: "32"
          AUTHORITY_HOST: "REPLACE_ME"
          AUTHORITY_USER: "REPLACE_ME"
          AUTHORITY_PASSWORD: "REPLACE_ME"
          AUTHORITY_CLIENT_ID: "authority"
          AUTHORITY_CLIENT_SECRET: "REPLACE_ME"
          AWS_ACCESS_KEY_INTEGRATION: "REPLACE_ME"
          AWS_SECRET_KEY_INTEGRATION: "REPLACE_ME"
          AWS_REGION_INTEGRATION: "ap-southeast-2"
          AWS_BUCKET_NAME: "REPLACE_ME"
          COMPLETED_EVENT_URL: "REPLACE_ME"
          COMPLETED_EVENT_API_KEY_VALUE: "REPLACE_ME"
          AUTHORITY_CONFIG_CONFIGFILE_NAME: "TenantConfigurations/11/AuthorityTaskConfig/config.json"
          ASSETIC_HOST: "REPLACE_ME"
          ASSETIC_API_BASIC: "REPLACE_ME"
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /crm
            Method: post




